### ISSUE TITLE
Instructions for setting up dev environment

### ISSUE THREAD

**Issue by niekvanderkooy** [JC5/firefly-iii#283]
I wanted to set up a dev environment in order to be able to contribute, but I keep running into errors. When I seed from `master` I catch a `DecryptException` in the `Preference` model (Probably introduced [here](https://github.com/JC5/firefly-iii/commit/cbe3fb73a88a0dbd246467d26e452e7537bbb65c)), while when seeding from `develop` I get problems in `AuthController::getBlockedDomains()` where the `blocked-domains` config does not seem to exist.

How do I properly get a working dev environment up and running?

**Comment by JC5** [comment]
Seeding from develop/master, are you running the migrations + seed?

I'll set up a new environment and see what's happening :)

**Comment by JC5** [comment]
If you have a stacktrace, I can find out what code is trying to decrypt a non-existing preference.

**Comment by JC5** [comment]
The problem with the blocked domains should be fixed.

**Comment by niekvanderkooy** [comment]
Blocked domains indeed seems to be fixed. Decrypting problem still exists, now also when running the migration/seed from develop.

Error message: `Could not decrypt preference #3.`

```
Error

This error occured in file E:\wamp\www\firefly-dev\app\Models\Preference.php on line 57 with code 0.

Stack trace
#0 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2720): FireflyIII\Models\Preference->getDataAttribute('')
#1 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2622): Illuminate\Database\Eloquent\Model->mutateAttribute('data', '')
#2 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2602): Illuminate\Database\Eloquent\Model->getAttributeValue('data')
#3 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(3395): Illuminate\Database\Eloquent\Model->getAttribute('data')
#4 E:\wamp\www\firefly-dev\app\Http\Middleware\AuthenticateTwoFactor.php(54): Illuminate\Database\Eloquent\Model->__get('data')
#5 [internal function]: FireflyIII\Http\Middleware\AuthenticateTwoFactor->handle(Object(Illuminate\Http\Request), Object(Closure))
#6 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 E:\wamp\www\firefly-dev\app\Http\Middleware\Authenticate.php(51): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 [internal function]: FireflyIII\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#17 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#22 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#27 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#32 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#34 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#37 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#41 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Routing\Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#42 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Routing\Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#43 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Routing\Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#44 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#45 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#46 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#47 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#50 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#52 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#54 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#55 E:\wamp\www\firefly-dev\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#56 E:\wamp\www\firefly-dev\public\index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#57 {main}
```

**Comment by JC5** [comment]
Can't seem to reproduce it this evening. Try the following. Surf to /flush. Run php artisan cache:clear. Login again if necessary.

There's a new commit with some debug stuff. It might give us some more intel. Could be that NULL values are not handled properly. Next quest would be to find out where I'm storing NULL values. Which should not be possible.

**Comment by niekvanderkooy** [comment]
Hmm, yeah, a cache:clear seems to fix it, and repeating what I did this morning from memory doesn't seem to bring it back. I'll close it for now, and I'll let you know if it happens again :-P
